def capture_daily_po_rec_snapshot():
	from prakash_steel.prakash_steel.doctype.purchase_order_recommendation_snapshot.purchase_order_recommendation_snapshot import capture_daily_po_rec_snapshot as _run
	_run()
